version: '3.8'
services:
  app:
    container_name: app
    restart: unless-stopped
    build: .
    ports:
    - "3000:3000"
    links:
    - mongo
    depends_on:
      - mongo
    environment:
      - MONGO_DB_URI=mongodb://admin:secret@mongo:27017/admin

  mongo:
    container_name: mongo
    image: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
    - ./data:/data/db
    ports:
    - '27017:27017'